PROGS_CYCLONE_OBJS := cyclone.o
PROGS_CYCLONE_OBJS := $(PROGS_CYCLONE_OBJS:%=$(TDIR)/cyclone/%)
ALL_OBJS += $(PROGS_CYCLONE_OBJS)

$(TDIR)/bin/cyclone : $(TSTART) $(PROGS_CYCLONE_OBJS) $(TLIBC)

